version: "3.9"

services:
  ticketdb:
    image: postgres:12
    volumes:
      - ticketdb-app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  ticketdb-app-db-data: